import { useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, CircleDashed, FlaskConical, Info } from "lucide-react";
import {
  METRIC_KEYS, METRIC_LABELS, VALIDATION_LABELS, publicShotResult,
  type AnalysisResultV1, type MetricKey, type MetricStatus,
} from "../../lib/analysis/contract";
import { GOAL_LABELS, type SessionRow } from "../../lib/api/types";
import { resultSummary } from "../../lib/analysis/resultSummary";
import { buildCoachingReport } from "../../lib/analysis/coaching";
import { BLUE_SKY, BORDER, INK, NEON, ORANGE, ORANGE_L, ROSE, VIOLET, WHITE_DIM, WHITE_SUB } from "../theme";
import { Card, Notice, Pill, WidgetHeader } from "../shell/primitives";
import { CourtDwellHeatmap } from "./CourtDwellHeatmap";
import { CoachingPanel, type PreviousSession } from "./CoachingPanel";
import { PlayerPicker } from "./PlayerPicker";
import { ShotsPanel } from "./ShotsPanel";
import { VideoOverlayPlayer, type JumpRequest } from "./VideoOverlayPlayer";
import { courtPlayers, focusShots } from "../../lib/analysis/shotLabels";

const STATUS_COLORS: Record<MetricStatus, string> = {
  measured: NEON,
  insufficient_data: ORANGE,
  not_computed: WHITE_SUB,
  experimental: VIOLET,
};
const STATUS_TEXT: Record<MetricStatus, string> = {
  measured: "Measured",
  insufficient_data: "Insufficient data",
  not_computed: "Not computed",
  experimental: "Experimental",
};

const fmtS = (s: number | null | undefined) => (s == null ? "unknown" : `${s.toFixed(1)} s`);
const pct = (f: number | null | undefined) => (f == null ? "unknown" : `${Math.round(f * 100)}%`);

function downloadResult(result: AnalysisResultV1) {
  const name = (result.provenance.source.filename ?? "video").replace(/\.[^.]+$/, "");
  const url = URL.createObjectURL(new Blob([JSON.stringify(result, null, 2)], { type: "application/json" }));
  const a = document.createElement("a");
  a.href = url;
  a.download = `${name}.result.json`;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/** Keep in-report navigation separate from the application's HashRouter. */
function focusReportSection(id: string) {
  const target = document.getElementById(id);
  if (!target) return;
  if (target instanceof HTMLDetailsElement) target.open = true;
  target.scrollIntoView?.({ behavior: "smooth", block: "start" });
  target.focus({ preventScroll: true });
}

/** Results written by the development-only Dev mode button. */
export const isDevMock = (result: AnalysisResultV1) => result.provenance.pipeline_version === "dev-mock";

export function OriginBadge({ origin, devMock = false }: { origin: AnalysisResultV1["data_origin"]; devMock?: boolean }) {
  if (devMock) {
    return (
      <Pill color={ORANGE} title="Generated by Dev mode for testing. It is not an analysis of any video.">
        <FlaskConical size={10} /> DEV MOCK DATA — NOT A REAL ANALYSIS
      </Pill>
    );
  }
  return origin === "test_fixture" ? (
    <Pill color={ROSE} title="Canned result produced by the worker's test mode. It is not an analysis of this video.">
      <FlaskConical size={10} /> TEST DATA — NOT FROM YOUR VIDEO
    </Pill>
  ) : (
    <Pill color={NEON} title="Computed by the analysis pipeline from this video.">MEASURED FROM THIS VIDEO</Pill>
  );
}

/** The player the user said they are, remembered per session in this browser. */
function useMyPlayer(key: string, analysed: number | null): [number | null, (id: number) => void] {
  const read = () => {
    try {
      const saved = window.localStorage.getItem(key);
      return saved != null && /^\d+$/.test(saved) ? Number(saved) : analysed;
    } catch {
      return analysed;
    }
  };
  const [id, setId] = useState<number | null>(read);
  useEffect(() => setId(read()), [key, analysed]); // eslint-disable-line react-hooks/exhaustive-deps
  const choose = (next: number) => {
    setId(next);
    try { window.localStorage.setItem(key, String(next)); } catch { /* private mode: keep it for this visit */ }
  };
  return [id, choose];
}

function Row({ k, v }: { k: string; v: React.ReactNode }) {
  return (
    <div className="flex justify-between gap-3 py-1.5 border-b text-sm" style={{ borderColor: BORDER }}>
      <span style={{ color: WHITE_DIM }}>{k}</span>
      <span className="font-mono text-right" style={{ color: INK }}>{v}</span>
    </div>
  );
}

export function ResultView({ result, videoUrl, previous, session, onSelectTrack, experimentalReview = false }: {
  result: AnalysisResultV1; videoUrl: string | null; previous?: PreviousSession | null;
  session?: SessionRow; onSelectTrack?: (trackId: number, timeSeconds: number) => void;
  /** Research-only local prototype. Never used by saved player reports. */
  experimentalReview?: boolean;
}) {
  const c = result.coverage;
  const heat = result.metrics.court_heatmap;
  const zones = result.metrics.zone_occupancy;
  const sel = result.player_selection;
  const coaching = buildCoachingReport(result);
  const summary = resultSummary(result);
  const [selectingPlayer, setSelectingPlayer] = useState(false);
  const [jump, setJump] = useState<JumpRequest>(null);
  const shotMetric = result.metrics.shot_classification;
  const shotDisplayResult = experimentalReview ? result : publicShotResult(result);
  const shotsValidated = result.data_origin === "measured" && shotMetric.validation === "evaluated_on_real_footage";
  // Team direction (30 Sep 2026): show shot estimates in saved reports too,
  // marked experimental until they pass evaluation on labelled real footage.
  const allowShotDisplay = true;
  const shotsShown = allowShotDisplay && !!shotMetric.value?.shots.length;
  const analysedId = sel?.method === "track_id" ? sel.track_id : null;
  const [myPlayerId, setMyPlayerId] = useMyPlayer(
    `picklepro:me:${session?.id ?? result.provenance.source.sha256 ?? result.provenance.generated_at}`, analysedId);
  const hasPlayers = courtPlayers(result).length > 0;
  // Older saved reports included an experimental hit count in the summary.
  // Keep that count hidden until the shot detector has real-footage evaluation.
  const visibleMessage = shotsValidated ? result.message
    : result.message.replace(/\s+\d+ hits? were estimated from the ball's flight\./, "");
  const shotCount = focusShots(shotDisplayResult, myPlayerId);
  const devMock = isDevMock(result);
  const heatValidated = devMock || heat.validation === "evaluated_on_real_footage";
  const zonesValidated = devMock || zones.validation === "evaluated_on_real_footage";
  const warnings = devMock ? result.warnings.filter((warning) => !warning.startsWith("DEV MOCK DATA")) : result.warnings;
  const showCoaching = !session?.improvement_goals?.length || session.improvement_goals.includes("positioning");
  const nextAction = hasPlayers && myPlayerId == null
    ? { label: "Choose your player", target: "player-review" }
    : result.calibration?.quality !== "good" && videoUrl
      ? { label: result.calibration ? "Check the court lines" : "Review the camera view", target: "video-heading" }
      : shotsShown ? { label: "Review the named hits", target: "named-hits" }
        : showCoaching ? { label: coaching.available ? "Start your practice plan" : "Explore general practice", target: "practice-plan" }
          : { label: "Review analysis details", target: "result-details" };

  return (
    <div id="feedback" className="space-y-4 scroll-mt-6" data-testid="result-view">
      {result.data_origin === "test_fixture" && (
        <Notice tone="error">
          <strong>Test data.</strong> This result was produced by the worker's test mode from a synthetic clip. None
          of the numbers below describe your video.
        </Notice>
      )}

      <Card accent={result.status === "ok" ? NEON : ORANGE}>
        <h2 className="mb-3 text-xl font-bold text-[#101827]">Your video review</h2>
        <div className="flex flex-wrap items-center gap-2 mb-2">
          <OriginBadge origin={result.data_origin} devMock={devMock} />
          <Pill color={devMock ? ORANGE : result.status === "ok" ? NEON : ORANGE}>
            {devMock ? "SAMPLE" : result.status === "ok" ? "RESULT" : "INSUFFICIENT DATA"}
          </Pill>
        </div>
        <p className="text-base text-[#101827]">{summary
          ? shotsShown ? "Review the named hits, check what the video could show, then choose a practice action."
            : "Some findings need your review. No named hits are available; this does not mean no hits occurred."
          : devMock ? "This sample shows the kind of practice plan PicklePro can display. It is not feedback about your play." : visibleMessage}</p>
        {summary && <>
          <p className="mt-2 text-sm" style={{ color: ORANGE_L }}>These findings are estimates. Shot success, in/out calls and technique are not assessed.{c.fraction_of_video_analyzed != null && c.fraction_of_video_analyzed < .99 ? " Only part of this video was analyzed." : ""}</p>
          <nav aria-label="Your next action" className="mt-4">
            <button type="button" aria-controls={nextAction.target} onClick={() => focusReportSection(nextAction.target)}
              className="inline-flex min-h-[44px] items-center rounded-lg px-4 py-2 text-sm font-semibold" style={{ background: BLUE_SKY, color: "white" }}>{nextAction.label}</button>
          </nav>
        </>}
      </Card>

      <div className="grid items-start gap-5 lg:grid-cols-[minmax(0,1.25fr)_minmax(0,1fr)]">
        <Card>
          <section aria-labelledby="video-heading" className="space-y-3 min-w-0">
            <div>
              <h2 id="video-heading" tabIndex={-1} className="text-lg font-bold text-[#101827]">Review your video</h2>
              <p className="text-base" style={{ color: WHITE_DIM }}>Press play to review the recording. Player boxes, observed ball positions and court lines are shown when available.{shotsValidated ? " Evaluated shot estimates are also shown." : " Experimental shot estimates are also shown; check them against the video."}</p>
            </div>
            {videoUrl && onSelectTrack && result.tracks.length > 0 && (
              <div className="flex flex-wrap items-center gap-2">
                <button type="button" onClick={() => setSelectingPlayer((value) => !value)}
                  className="rounded-lg px-4 py-2.5 text-sm font-semibold min-h-[44px]" style={{ background: BLUE_SKY, color: "#ffffff" }}>
                  {selectingPlayer ? "Cancel" : "Not you? Pick yourself in the video"}
                </button>
                {selectingPlayer && <p className="text-base" style={{ color: INK }}>Pause the video where you can be seen, then tap the box around you. PicklePro will check the video again for you.</p>}
              </div>
            )}
            <VideoOverlayPlayer src={videoUrl}
              positions={heatValidated || selectingPlayer || hasPlayers ? result.player_positions : []}
              ballPositions={result.ball_positions ?? []}
              courtLines={result.court_lines ?? []} shots={allowShotDisplay ? shotDisplayResult.metrics.shot_classification.value?.shots ?? [] : []}
              bounces={allowShotDisplay ? shotMetric.value?.bounces ?? [] : []}
              selectedTrackId={myPlayerId} jump={jump}
              onSelectTrack={selectingPlayer ? (id, time) => { setSelectingPlayer(false); setMyPlayerId(id); onSelectTrack?.(id, time); } : undefined} />
          </section>

          {result.data_origin === "measured" && !devMock && hasPlayers && (
            <div id="player-review" tabIndex={-1} className="scroll-mt-6"><PlayerPicker result={shotDisplayResult} myPlayerId={myPlayerId} onPick={setMyPlayerId} showShotCounts={allowShotDisplay}
              onUpdateCourt={onSelectTrack && myPlayerId != null ? () => {
                const me = result.players?.find((p) => p.player_id === myPlayerId);
                onSelectTrack(myPlayerId, me?.first_seen_s ?? 0);
              } : undefined} /></div>
          )}

        </Card>
        <section aria-label="Understand your results" className="min-w-0">
          <Card>
            <h2 className="text-lg font-bold" style={{ color: INK }}>Understand your results</h2>
            {result.data_origin === "measured" && !devMock && <section aria-label="What the video analysis found" className="space-y-0">
              <h2 className="sr-only">What PicklePro could see</h2>
              {[
                {
                  label: "Players",
                  ok: c.frames_with_detections > 0,
                  value: !result.provenance.detector.confidence_is_model_score
                    ? c.frames_with_detections > 0 ? "Movement detected" : "No movement detected"
                    : sel && sel.tracked_fraction > 0
                    ? `Found you in ${Math.round(sel.tracked_fraction * 100)}% of the video`
                    : c.frames_with_detections > 0 ? "Players found" : "No players found",
                  detail: result.provenance.detector.confidence_is_model_score
                    ? "Boxes on the video show who was found. \u201cYou\u201d is the player used for your feedback."
                    : "Only movement was detected, so boxes may not always be people.",
                },
                {
                  label: "Court",
                  ok: !!result.calibration,
                  value: result.calibration ? "Court lines found" : "Court not found",
                  detail: result.calibration
                    ? "Yellow lines on the video show where PicklePro thinks the court is."
                    : "Film so the whole court and its lines are visible to get court feedback.",
                },
                {
                  label: "Ball",
                  ok: (c.frames_with_ball_detections ?? 0) > 0,
                  value: !result.provenance.ball_detector ? "Ball finder not set up"
                    : (c.frames_with_ball_detections ?? 0) > 0 ? "Ball positions found" : "Ball not seen",
                  detail: result.provenance.ball_detector
                    ? "The orange dot and trail show where the ball was seen."
                    : "The analyzer needs a ball model to follow the ball.",
                },
                {
                  label: "Shots",
                  ok: shotsShown,
                  value: shotsShown
                    ? `${shotCount.shots.length} ${shotCount.mine ? "of your hits" : "hits"} named`
                    : "Not available",
                  detail: shotsShown
                    ? shotsValidated ? "Tap Watch next to a shot to check it."
                      : "Experimental: not yet checked against hand-labelled videos. Tap Watch to check a shot."
                    : !allowShotDisplay ? "Shot labels are hidden until they pass evaluation on labelled real footage."
                      : shotMetric.reason ?? "Shot types are not available for this video.",
                },
              ].map((item) => (
                <div key={item.label} className="border-b py-3" style={{ borderColor: BORDER }}>
                  <p className="flex items-center gap-2 text-sm font-bold uppercase tracking-wider" style={{ color: BLUE_SKY }}>
                    {item.ok ? <CheckCircle2 size={18} aria-label="found" style={{ color: NEON }} />
                      : <CircleDashed size={18} aria-label="not found" style={{ color: WHITE_SUB }} />}
                    {item.label}
                  </p>
                  <p className="mt-1 text-base font-bold" style={{ color: INK }}>{item.label === "Shots" && shotsShown
                    ? <button type="button" aria-controls="named-hits" onClick={() => focusReportSection("named-hits")} className="inline-flex min-h-[44px] items-center underline underline-offset-4" style={{ color: BLUE_SKY }}>{item.value}</button>
                    : item.value}</p>
                  <p className="mt-1 text-sm leading-relaxed" style={{ color: WHITE_DIM }}>{item.detail}</p>
                </div>
              ))}
            </section>}

            {summary && <div aria-label="Your result at a glance" className="mt-3 space-y-3">
              <h3 className="text-sm font-semibold" style={{ color: INK }}>What this video cannot tell you</h3>
              <ul className="list-disc space-y-1 pl-4 text-sm" style={{ color: WHITE_DIM }}>
                {summary.unavailable.map(item => <li key={item}>{item}</li>)}
              </ul>
              <details>
                <summary className="cursor-pointer py-2 text-sm font-semibold" style={{ color: BLUE_SKY }}>What to check against the video</summary>
                <ul className="list-disc space-y-1 pl-4 text-sm" style={{ color: WHITE_DIM }}>
                  {summary.needsReview.map(item => <li key={item}>{item}</li>)}
                </ul>
              </details>
            </div>}
            {!summary && <p className="mt-3 text-sm" style={{ color: ORANGE_L }}>Sample values are for demonstration only. They do not describe your play.</p>}
          </Card>
        </section>
      </div>
      {result.data_origin === "measured" && !devMock && allowShotDisplay && (
        <section id="named-hits" tabIndex={-1} aria-label="Review named hits" className="scroll-mt-6"><ShotsPanel result={shotDisplayResult} myPlayerId={myPlayerId} research={experimentalReview}
          onWatch={videoUrl ? (time) => setJump({ time, id: Date.now() }) : undefined} /></section>
      )}

      <section id="practice-plan" tabIndex={-1} aria-label="Choose what to practice" className="space-y-3 scroll-mt-6">
        <h2 className="text-lg font-bold" style={{ color: INK }}>Choose what to practice</h2>
        {showCoaching ? <CoachingPanel result={result} previous={previous} />
          : <Card><p className="text-base" style={{ color: INK }}>PicklePro cannot provide a practice plan for your selected technique or shot-outcome goals yet.</p>
            <p className="mt-2 text-sm" style={{ color: WHITE_DIM }}>Review the video yourself or with a coach. Your goals and starting ratings are saved below.</p></Card>}

      </section>
      {!!session?.improvement_goals?.length && <details className="rounded-xl border p-4" style={{ borderColor: BORDER }}>
        <summary className="cursor-pointer font-semibold" style={{ color: BLUE_SKY }}>Your goals and starting ratings</summary>
      {session?.improvement_goals?.length ? (
        <Card accent={BLUE_SKY}>
          <WidgetHeader title="Your goals and video evidence" subtitle="Your own skill ratings are separate from video measurements." />
          <ul className="space-y-2">
            {session.improvement_goals.map((goal) => {
              const rating = session[`${goal}_rating`];
              const observed = goal === "positioning" && coaching.available;
              const reason = goal === "positioning" ? coaching.introduction
                : goal === "shot_outcomes"
                  ? "Shot outcomes cannot be assessed. Shot success and in/out calls are outside this analysis scope."
                  : "Technique cannot be assessed yet. The current analysis does not measure body and paddle mechanics.";
              return <li key={goal} className="rounded-xl p-3 text-sm" style={{ border: `1px solid ${BORDER}` }}>
                <p className="text-base font-semibold text-[#101827]">{GOAL_LABELS[goal]} · {observed ? (goal === "positioning" ? "video feedback available" : "early estimate available") : "cannot assess from this analysis"}</p>
                <p className="mt-1" style={{ color: WHITE_DIM }}>Your starting rating: {rating ? `${rating}/5` : "not set"}</p>
                <p className="mt-1" style={{ color: observed ? NEON : ORANGE_L }}>{reason}</p>
              </li>;
            })}
          </ul>
        </Card>
      ) : null}

      </details>}
      <details id="result-details" tabIndex={-1} className="rounded-2xl p-4 scroll-mt-6" style={{ border: `1px solid ${BORDER}` }}>
        <summary className="cursor-pointer text-base font-semibold" style={{ color: BLUE_SKY }}>Analysis details</summary>
        <p className="mt-3 text-sm" style={{ color: WHITE_DIM }}>{visibleMessage}</p>
        {result.data_origin === "measured" && <button type="button" onClick={() => downloadResult(result)} className="mt-3 min-h-[44px] text-sm font-semibold underline"
          style={{ color: BLUE_SKY }} title="For the Label shots page and for scoring shot detection">Download research result (JSON)</button>}
        {warnings.length > 0 && <ul className="mt-3 space-y-1.5">
          {warnings.map(w => <li key={w} className="flex gap-2 text-sm" style={{ color: ORANGE_L }}><AlertTriangle size={14} className="mt-0.5 flex-shrink-0" aria-hidden="true" />{w}</li>)}
        </ul>}
        <div className="mt-3"><Pill color={BLUE_SKY}>{heat.scope === "selected_view" ? "SELECTED-VIEW METRICS" : "WHOLE-CLIP METRICS"}</Pill></div>
        <div className="mt-4 grid gap-4 lg:grid-cols-[1fr_340px]">
          <div className="space-y-4">

            <Card>
              <WidgetHeader title="Metrics" subtitle={heat.scope === "selected_view"
                ? "Court measures cover one camera view. Other estimates report their own scope and status."
                : "Each metric reports its own status and validation level."} />
              <ul className="space-y-2">
                {METRIC_KEYS.map((key: MetricKey) => {
                  const m = result.metrics[key];
                  return (
                    <li key={key} className="rounded-xl p-3" style={{ background: "rgba(41,61,242,0.025)", border: `1px solid ${BORDER}` }}>
                      <div className="flex flex-wrap items-center gap-2">
                        <span className="text-sm font-semibold text-[#101827]">{METRIC_LABELS[key]}</span>
                        <Pill color={STATUS_COLORS[m.status]}>{STATUS_TEXT[m.status].toUpperCase()}</Pill>
                        {m.status !== "not_computed" && <Pill color={WHITE_SUB}>{VALIDATION_LABELS[m.validation]}</Pill>}
                      </div>
                      {m.reason && <p className="text-sm mt-1" style={{ color: WHITE_DIM }}>{m.reason}</p>}
                    </li>
                  );
                })}
              </ul>
            </Card>
          </div>

          <div className="space-y-4">
            <Card>
              <WidgetHeader title="Court heatmap" subtitle="Where the selected player's feet were, weighted by time." />
              {heatValidated && heat.status === "measured" && heat.value ? (
                <>
                  <CourtDwellHeatmap value={heat.value} />
                  <div className="mt-3">
                    <Row k="Tracked time" v={fmtS(heat.value.tracked_time_s)} />
                    <Row k="Outside mapped area" v={fmtS(heat.value.outside_mapped_area_s)} />
                  </div>
                </>
              ) : (
                <p className="text-sm flex gap-2" style={{ color: ORANGE_L }}>
                  <Info size={12} className="flex-shrink-0 mt-0.5" /> {heatValidated ? heat.reason ?? "Not available." : "Hidden until positional accuracy passes evaluation on labelled real footage."}
                </p>
              )}
              {zonesValidated && zones.status === "experimental" && zones.value && (
                <div className="mt-4">
                  <div className="flex items-center gap-2 mb-1">
                    <span className="text-sm font-semibold text-[#101827]">Zone occupancy</span>
                    <Pill color={VIOLET}>EXPERIMENTAL</Pill>
                  </div>
                  {Object.entries(zones.value.fraction_of_tracked_time).map(([zone, f]) => (
                    <Row key={zone} k={zone.replace(/_/g, " ")} v={pct(f)} />
                  ))}
                </div>
              )}
            </Card>

            <Card>
              <WidgetHeader title="Provenance & coverage" subtitle="How this result was produced and how much of the video it covers." />
              <Row k="Origin" v={result.data_origin === "test_fixture" ? "test fixture" : "measured"} />
              <Row k="Pipeline version" v={result.provenance.pipeline_version} />
              <Row k="Detector" v={result.provenance.detector.name} />
              <Row k="Ball detector" v={result.provenance.ball_detector?.name ?? "not configured"} />
              <Row k="Detection confidence" v={result.provenance.detector.confidence_is_model_score ? "model score" : "not available"} />
              <Row k="Video length" v={fmtS(result.video.container_duration_s)} />
              <Row k="Analyzed" v={`${fmtS(c.analyzed_start_s)} – ${fmtS(c.analyzed_end_s)}`} />
              <Row k="Share of video analyzed" v={pct(c.fraction_of_video_analyzed)} />
              {c.selected_view_duration_s != null && <Row k="Selected camera view" v={fmtS(c.selected_view_duration_s)} />}
              <Row k="Frames analyzed" v={`${c.frames_analyzed} (every ${c.sample_stride}${c.sample_stride === 1 ? "" : "th"} frame)`} />
              <Row k="Frames with player detections" v={c.frames_with_detections} />
              <Row k="Frames with ball detections" v={c.frames_with_ball_detections ?? 0} />
              {c.decode_failures > 0 && <Row k="Undecodable frames" v={c.decode_failures} />}
              <Row k="Calibration" v={result.calibration
                ? result.calibration.method === "auto_painted_lines"
                  ? "automatic · checked against the painted lines in every frame"
                  : `${result.calibration.method === "auto_model_landmarks" ? "automatic" : result.calibration.method === "user_confirmed_landmarks" ? "user confirmed, checked against painted lines" : "manual"} · ${result.calibration.landmarks_used.length} landmarks · ${result.calibration.quality} (${result.calibration.reprojection_rmse_m.toFixed(2)} m)`
                : "none"} />
              <Row k="Player selection" v={sel
                ? `${sel.method === "court_half" ? `${sel.court_half} half` : `track #${sel.track_id}`} · tracked ${pct(sel.tracked_fraction)}`
                : "none"} />
              {result.tracks.length > 0 && <Row k="Player track IDs" v={result.tracks
                .slice().sort((a, b) => b.observed_frames - a.observed_frames)
                .slice(0, 8).map((track) => `#${track.track_id}`).join(", ")} />}
              <Row k="Generated" v={new Date(result.provenance.generated_at).toLocaleString()} />
              {result.provenance.source.filename && <Row k="Source file" v={result.provenance.source.filename} />}
            </Card>
          </div>
        </div>
      </details>
    </div>
  );
}
