import { useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, CircleDashed, FlaskConical, Info } from "lucide-react";
import {
  METRIC_KEYS, METRIC_LABELS, VALIDATION_LABELS,
  type AnalysisResultV1, type MetricKey, type MetricStatus,
} from "../../lib/analysis/contract";
import { GOAL_LABELS, type SessionRow } from "../../lib/api/types";
import { buildCoachingReport } from "../../lib/analysis/coaching";
import { BLUE_SKY, BORDER, INK, NEON, ORANGE, ORANGE_L, ROSE, VIOLET, WHITE_DIM, WHITE_SUB } from "../theme";
import { Card, Notice, Pill, WidgetHeader } from "../shell/primitives";
import { CourtDwellHeatmap } from "./CourtDwellHeatmap";
import { CoachingPanel, type PreviousSession } from "./CoachingPanel";
import { PlayerPicker } from "./PlayerPicker";
import { ShotsPanel } from "./ShotsPanel";
import { VideoOverlayPlayer, type JumpRequest } from "./VideoOverlayPlayer";
import { courtPlayers, focusShots } from "../../lib/analysis/shotLabels";

const STATUS_COLORS: Record<MetricStatus, string> = {
  measured: NEON,
  insufficient_data: ORANGE,
  not_computed: WHITE_SUB,
  experimental: VIOLET,
};
const STATUS_TEXT: Record<MetricStatus, string> = {
  measured: "Measured",
  insufficient_data: "Insufficient data",
  not_computed: "Not computed",
  experimental: "Experimental",
};

const fmtS = (s: number | null | undefined) => (s == null ? "unknown" : `${s.toFixed(1)} s`);
const pct = (f: number | null | undefined) => (f == null ? "unknown" : `${Math.round(f * 100)}%`);

/** Results written by the development-only Dev mode button. */
export const isDevMock = (result: AnalysisResultV1) => result.provenance.pipeline_version === "dev-mock";

export function OriginBadge({ origin, devMock = false }: { origin: AnalysisResultV1["data_origin"]; devMock?: boolean }) {
  if (devMock) {
    return (
      <Pill color={ORANGE} title="Generated by Dev mode for testing. It is not an analysis of any video.">
        <FlaskConical size={10} /> DEV MOCK DATA — NOT A REAL ANALYSIS
      </Pill>
    );
  }
  return origin === "test_fixture" ? (
    <Pill color={ROSE} title="Canned result produced by the worker's test mode. It is not an analysis of this video.">
      <FlaskConical size={10} /> TEST DATA — NOT FROM YOUR VIDEO
    </Pill>
  ) : (
    <Pill color={NEON} title="Computed by the analysis pipeline from this video.">MEASURED FROM THIS VIDEO</Pill>
  );
}

/** The player the user said they are, remembered per session in this browser. */
function useMyPlayer(key: string, analysed: number | null): [number | null, (id: number) => void] {
  const read = () => {
    try {
      const saved = window.localStorage.getItem(key);
      return saved != null && /^\d+$/.test(saved) ? Number(saved) : analysed;
    } catch {
      return analysed;
    }
  };
  const [id, setId] = useState<number | null>(read);
  useEffect(() => setId(read()), [key, analysed]); // eslint-disable-line react-hooks/exhaustive-deps
  const choose = (next: number) => {
    setId(next);
    try { window.localStorage.setItem(key, String(next)); } catch { /* private mode: keep it for this visit */ }
  };
  return [id, choose];
}

function Row({ k, v }: { k: string; v: React.ReactNode }) {
  return (
    <div className="flex justify-between gap-3 py-1.5 border-b text-sm" style={{ borderColor: BORDER }}>
      <span style={{ color: WHITE_DIM }}>{k}</span>
      <span className="font-mono text-right" style={{ color: INK }}>{v}</span>
    </div>
  );
}

export function ResultView({ result, videoUrl, previous, session, onSelectTrack }: {
  result: AnalysisResultV1; videoUrl: string | null; previous?: PreviousSession | null;
  session?: SessionRow; onSelectTrack?: (trackId: number, timeSeconds: number) => void;
}) {
  const c = result.coverage;
  const heat = result.metrics.court_heatmap;
  const zones = result.metrics.zone_occupancy;
  const sel = result.player_selection;
  const coaching = buildCoachingReport(result);
  const [selectingPlayer, setSelectingPlayer] = useState(false);
  const [jump, setJump] = useState<JumpRequest>(null);
  const shotMetric = result.metrics.shot_classification;
  const shotsValidated = shotMetric.validation === "evaluated_on_real_footage";
  // Experimental shot labels are shown, clearly marked, so they can be checked against the video.
  const shotsShown = !!shotMetric.value?.shots.length;
  const analysedId = sel?.method === "track_id" ? sel.track_id : null;
  const [myPlayerId, setMyPlayerId] = useMyPlayer(
    `picklepro:me:${session?.id ?? result.provenance.source.sha256 ?? result.provenance.generated_at}`, analysedId);
  const hasPlayers = courtPlayers(result).length > 0;
  // Older saved reports included an experimental hit count in the summary.
  // Keep that count hidden until the shot detector has real-footage evaluation.
  const visibleMessage = shotsValidated ? result.message
    : result.message.replace(/\s+\d+ hits? were estimated from the ball's flight\./, "");
  const shotCount = focusShots(result, myPlayerId);
  const devMock = isDevMock(result);
  const heatValidated = devMock || heat.validation === "evaluated_on_real_footage";
  const zonesValidated = devMock || zones.validation === "evaluated_on_real_footage";
  const warnings = devMock ? result.warnings.filter((warning) => !warning.startsWith("DEV MOCK DATA")) : result.warnings;

  return (
    <div id="feedback" className="space-y-4 scroll-mt-6" data-testid="result-view">
      {result.data_origin === "test_fixture" && (
        <Notice tone="error">
          <strong>Test data.</strong> This result was produced by the worker's test mode from a synthetic clip. None
          of the numbers below describe your video.
        </Notice>
      )}

      <Card accent={result.status === "ok" ? NEON : ORANGE}>
        <h2 className="mb-3 text-xl font-bold text-[#101827]">What PicklePro could assess</h2>
        <div className="flex flex-wrap items-center gap-2 mb-2">
          <OriginBadge origin={result.data_origin} devMock={devMock} />
          <Pill color={devMock ? ORANGE : result.status === "ok" ? NEON : ORANGE}>
            {devMock ? "SAMPLE" : result.status === "ok" ? "RESULT" : "INSUFFICIENT DATA"}
          </Pill>
        </div>
        <p className="text-base text-[#101827]">{devMock ? "This sample shows the kind of practice plan PicklePro can display. It is not feedback about your play." : visibleMessage}</p>
        {warnings.length > 0 && (
          <details className="mt-3">
            <summary className="cursor-pointer text-sm font-semibold" style={{ color: ORANGE_L }}>
              {warnings.length === 1 ? "1 note about this video" : `${warnings.length} notes about this video`}
            </summary>
            <ul className="mt-2 space-y-1.5">
              {warnings.map((w) => (
                <li key={w} className="text-sm flex gap-2" style={{ color: ORANGE_L }}>
                  <AlertTriangle size={14} className="flex-shrink-0 mt-0.5" aria-hidden="true" /> {w}
                </li>
              ))}
            </ul>
          </details>
        )}
      </Card>

      {result.data_origin === "measured" && !devMock && <section aria-label="What the video analysis found" className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        <h2 className="sr-only">What PicklePro could see</h2>
        {[
          {
            label: "Players",
            ok: c.frames_with_detections > 0,
            value: sel && sel.tracked_fraction > 0
              ? `Found you in ${Math.round(sel.tracked_fraction * 100)}% of the video`
              : c.frames_with_detections > 0 ? "Players found" : "No players found",
            detail: result.provenance.detector.confidence_is_model_score
              ? "Boxes on the video show who was found. \u201cYou\u201d is the player used for your feedback."
              : "Only movement was detected, so boxes may not always be people.",
          },
          {
            label: "Court",
            ok: !!result.calibration,
            value: result.calibration ? "Court lines found" : "Court not found",
            detail: result.calibration
              ? "Yellow lines on the video show where PicklePro thinks the court is."
              : "Film so the whole court and its lines are visible to get court feedback.",
          },
          {
            label: "Ball",
            ok: (c.frames_with_ball_detections ?? 0) > 0,
            value: !result.provenance.ball_detector ? "Ball finder not set up"
              : (c.frames_with_ball_detections ?? 0) > 0 ? "Ball followed" : "Ball not seen",
            detail: result.provenance.ball_detector
              ? "The orange dot and trail show where the ball was seen."
              : "The analyzer needs a ball model to follow the ball.",
          },
          {
            label: "Shots",
            ok: shotsShown,
            value: shotsShown
              ? `${shotCount.shots.length} ${shotCount.mine ? "of your hits" : "hits"} named`
              : "Not available",
            detail: shotsShown
              ? shotsValidated ? "Tap Watch next to a shot to check it."
                : "Experimental: not yet checked against hand-labelled videos. Tap Watch to check a shot."
              : shotMetric.reason ?? "Shot types are not available for this video.",
          },
        ].map((item) => (
          <div key={item.label} className="rounded-2xl border bg-white p-4" style={{ borderColor: BORDER }}>
            <p className="flex items-center gap-2 text-sm font-bold uppercase tracking-wider" style={{ color: BLUE_SKY }}>
              {item.ok ? <CheckCircle2 size={18} aria-label="found" style={{ color: NEON }} />
                : <CircleDashed size={18} aria-label="not found" style={{ color: WHITE_SUB }} />}
              {item.label}
            </p>
            <p className="mt-2 text-lg font-bold" style={{ color: INK }}>{item.value}</p>
            <p className="mt-1 text-sm leading-relaxed" style={{ color: WHITE_DIM }}>{item.detail}</p>
          </div>
        ))}
      </section>}

      {session?.improvement_goals?.length ? (
        <Card accent={BLUE_SKY}>
          <WidgetHeader title="Your goals and video evidence" subtitle="Your own skill ratings are separate from video measurements." />
          <ul className="space-y-2">
            {session.improvement_goals.map((goal) => {
              const rating = session[`${goal}_rating`];
              const shotsAvailable = shotsShown;
              const observed = (goal === "positioning" && coaching.available) || (goal === "shot_outcomes" && shotsAvailable);
              const reason = goal === "positioning" ? coaching.introduction
                : goal === "shot_outcomes"
                  ? shotsAvailable
                    ? "See the estimated shot types below. Ball landing and shot success are not assessed."
                    : "Shot outcomes cannot be assessed. Shot success and in/out calls are outside this analysis scope."
                  : "Technique cannot be assessed yet. The current analysis does not measure body and paddle mechanics.";
              return <li key={goal} className="rounded-xl p-3 text-sm" style={{ border: `1px solid ${BORDER}` }}>
                <p className="text-base font-semibold text-[#101827]">{GOAL_LABELS[goal]} · {observed ? (goal === "positioning" ? "video feedback available" : "early estimate available") : "cannot assess from this analysis"}</p>
                <p className="mt-1" style={{ color: WHITE_DIM }}>Your starting rating: {rating ? `${rating}/5` : "not set"}</p>
                <p className="mt-1" style={{ color: observed ? NEON : ORANGE_L }}>{reason}</p>
              </li>;
            })}
          </ul>
        </Card>
      ) : null}

      {(!session?.improvement_goals?.length || session.improvement_goals.includes("positioning")) &&
        <CoachingPanel result={result} previous={previous} />}

      {result.data_origin === "measured" && !devMock && hasPlayers && (
        <PlayerPicker result={result} myPlayerId={myPlayerId} onPick={setMyPlayerId}
          onUpdateCourt={onSelectTrack && myPlayerId != null ? () => {
            const me = result.players?.find((p) => p.player_id === myPlayerId);
            onSelectTrack(myPlayerId, me?.first_seen_s ?? 0);
          } : undefined} />
      )}

      <section aria-labelledby="video-heading" className="space-y-3">
        <div>
          <h2 id="video-heading" className="text-lg font-bold text-[#101827]">Watch your video</h2>
          <p className="text-base" style={{ color: WHITE_DIM }}>Press play to review the recording. Player numbers, the ball's trail and each estimated shot name are drawn on the video.</p>
        </div>
        {videoUrl && onSelectTrack && result.tracks.length > 0 && (
          <div className="flex flex-wrap items-center gap-2">
            <button type="button" onClick={() => setSelectingPlayer((value) => !value)}
              className="rounded-lg px-4 py-2.5 text-sm font-semibold min-h-[44px]" style={{ background: BLUE_SKY, color: "#ffffff" }}>
              {selectingPlayer ? "Cancel" : "Not you? Pick yourself in the video"}
            </button>
            {selectingPlayer && <p className="text-base" style={{ color: INK }}>Pause the video where you can be seen, then tap the box around you. PicklePro will check the video again for you.</p>}
          </div>
        )}
        <VideoOverlayPlayer src={videoUrl}
          positions={heatValidated || selectingPlayer || hasPlayers ? result.player_positions : []}
          ballPositions={result.ball_positions ?? []}
          courtLines={result.court_lines ?? []} shots={shotMetric.value?.shots ?? []}
          bounces={shotMetric.value?.bounces ?? []}
          selectedTrackId={myPlayerId} jump={jump}
          onSelectTrack={selectingPlayer ? (id, time) => { setSelectingPlayer(false); setMyPlayerId(id); onSelectTrack?.(id, time); } : undefined} />
      </section>

      {result.data_origin === "measured" && !devMock && (
        <ShotsPanel result={result} myPlayerId={myPlayerId} onWatch={videoUrl ? (time) => setJump({ time, id: Date.now() }) : undefined} />
      )}

      <details className="rounded-2xl p-4" style={{ border: `1px solid ${BORDER}` }}>
        <summary className="cursor-pointer text-base font-semibold" style={{ color: BLUE_SKY }}>Detailed measurements and analysis notes</summary>
        <div className="mt-3"><Pill color={BLUE_SKY}>{heat.scope === "selected_view" ? "SELECTED-VIEW METRICS" : "WHOLE-CLIP METRICS"}</Pill></div>
        <div className="mt-4 grid gap-4 lg:grid-cols-[1fr_340px]">
          <div className="space-y-4">

            <Card>
              <WidgetHeader title="Metrics" subtitle={heat.scope === "selected_view"
                ? "Court measures cover one camera view. Shot and rally findings are not available."
                : "Each metric reports its own status. Nothing here is a rally-level or shot-level finding."} />
              <ul className="space-y-2">
                {METRIC_KEYS.map((key: MetricKey) => {
                  const m = result.metrics[key];
                  return (
                    <li key={key} className="rounded-xl p-3" style={{ background: "rgba(41,61,242,0.025)", border: `1px solid ${BORDER}` }}>
                      <div className="flex flex-wrap items-center gap-2">
                        <span className="text-sm font-semibold text-[#101827]">{METRIC_LABELS[key]}</span>
                        <Pill color={STATUS_COLORS[m.status]}>{STATUS_TEXT[m.status].toUpperCase()}</Pill>
                        {m.status !== "not_computed" && <Pill color={WHITE_SUB}>{VALIDATION_LABELS[m.validation]}</Pill>}
                      </div>
                      {m.reason && <p className="text-sm mt-1" style={{ color: WHITE_DIM }}>{m.reason}</p>}
                    </li>
                  );
                })}
              </ul>
            </Card>
          </div>

          <div className="space-y-4">
            <Card>
              <WidgetHeader title="Court heatmap" subtitle="Where the selected player's feet were, weighted by time." />
              {heatValidated && heat.status === "measured" && heat.value ? (
                <>
                  <CourtDwellHeatmap value={heat.value} />
                  <div className="mt-3">
                    <Row k="Tracked time" v={fmtS(heat.value.tracked_time_s)} />
                    <Row k="Outside mapped area" v={fmtS(heat.value.outside_mapped_area_s)} />
                  </div>
                </>
              ) : (
                <p className="text-sm flex gap-2" style={{ color: ORANGE_L }}>
                  <Info size={12} className="flex-shrink-0 mt-0.5" /> {heatValidated ? heat.reason ?? "Not available." : "Hidden until positional accuracy passes evaluation on labelled real footage."}
                </p>
              )}
              {zonesValidated && zones.status === "experimental" && zones.value && (
                <div className="mt-4">
                  <div className="flex items-center gap-2 mb-1">
                    <span className="text-sm font-semibold text-[#101827]">Zone occupancy</span>
                    <Pill color={VIOLET}>EXPERIMENTAL</Pill>
                  </div>
                  {Object.entries(zones.value.fraction_of_tracked_time).map(([zone, f]) => (
                    <Row key={zone} k={zone.replace(/_/g, " ")} v={pct(f)} />
                  ))}
                </div>
              )}
            </Card>

            <Card>
              <WidgetHeader title="Provenance & coverage" subtitle="How this result was produced and how much of the video it covers." />
              <Row k="Origin" v={result.data_origin === "test_fixture" ? "test fixture" : "measured"} />
              <Row k="Pipeline version" v={result.provenance.pipeline_version} />
              <Row k="Detector" v={result.provenance.detector.name} />
              <Row k="Ball detector" v={result.provenance.ball_detector?.name ?? "not configured"} />
              <Row k="Detection confidence" v={result.provenance.detector.confidence_is_model_score ? "model score" : "not available"} />
              <Row k="Video length" v={fmtS(result.video.container_duration_s)} />
              <Row k="Analyzed" v={`${fmtS(c.analyzed_start_s)} – ${fmtS(c.analyzed_end_s)}`} />
              <Row k="Share of video analyzed" v={pct(c.fraction_of_video_analyzed)} />
              {c.selected_view_duration_s != null && <Row k="Selected camera view" v={fmtS(c.selected_view_duration_s)} />}
              <Row k="Frames analyzed" v={`${c.frames_analyzed} (every ${c.sample_stride}${c.sample_stride === 1 ? "" : "th"} frame)`} />
              <Row k="Frames with player detections" v={c.frames_with_detections} />
              <Row k="Frames with ball detections" v={c.frames_with_ball_detections ?? 0} />
              {c.decode_failures > 0 && <Row k="Undecodable frames" v={c.decode_failures} />}
              <Row k="Calibration" v={result.calibration
                ? `${result.calibration.method === "auto_model_landmarks" ? "automatic" : "manual"} · ${result.calibration.landmarks_used.length} landmarks · ${result.calibration.quality} (${result.calibration.reprojection_rmse_m.toFixed(2)} m)`
                : "none"} />
              <Row k="Player selection" v={sel
                ? `${sel.method === "court_half" ? `${sel.court_half} half` : `track #${sel.track_id}`} · tracked ${pct(sel.tracked_fraction)}`
                : "none"} />
              {result.tracks.length > 0 && <Row k="Player track IDs" v={result.tracks
                .slice().sort((a, b) => b.observed_frames - a.observed_frames)
                .slice(0, 8).map((track) => `#${track.track_id}`).join(", ")} />}
              <Row k="Generated" v={new Date(result.provenance.generated_at).toLocaleString()} />
              {result.provenance.source.filename && <Row k="Source file" v={result.provenance.source.filename} />}
            </Card>
          </div>
        </div>
      </details>
    </div>
  );
}
