-- Dev-mode mock data must look like a normal published report since the
-- versioned-run migration: each mock job gets run 1, the job points to it as
-- its current run, and the session publishes it as the active report. Without
-- this, mock sessions have an empty run history and no active report.
--
-- Same limits as before: anonymous callers only, only the caller's own rows,
-- every result marked provenance.pipeline_version = 'dev-mock', and reseeding
-- replaces the caller's earlier '[Dev mock]' sessions.

create or replace function public.seed_dev_mock_data(p_sessions jsonb)
returns int
language plpgsql security definer set search_path = '' as $$
declare
  uid uuid := auth.uid();
  s jsonb;
  r jsonb;
  v_session uuid;
  v_video uuid;
  v_job uuid;
  v_run uuid;
  n int := 0;
begin
  if uid is null or coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) is not true then
    raise exception 'dev_mock_requires_anonymous_user' using errcode = '42501',
      hint = 'Mock data can only be created for a Dev mode (anonymous) sign-in.';
  end if;
  if p_sessions is null or jsonb_typeof(p_sessions) <> 'array'
     or jsonb_array_length(p_sessions) not between 1 and 10 then
    raise exception 'invalid_mock_sessions' using errcode = '22023';
  end if;

  -- Replace, not accumulate. Cascades remove videos, jobs, runs and results.
  delete from public.sessions where owner_id = uid and title like '[Dev mock]%';

  for s in select * from jsonb_array_elements(p_sessions) loop
    r := s -> 'result';
    if r ->> 'schema_version' is null
       or coalesce(r ->> 'status', '') not in ('ok', 'insufficient_data')
       or coalesce(r ->> 'data_origin', '') not in ('measured', 'test_fixture')
       or r #>> '{provenance,pipeline_version}' is distinct from 'dev-mock' then
      raise exception 'invalid_mock_result' using errcode = '22023',
        hint = 'Mock results must be valid v1 results with provenance.pipeline_version = dev-mock.';
    end if;

    insert into public.sessions (owner_id, title, session_date, session_context, play_format, notes)
    values (uid, '[Dev mock] ' || left(coalesce(s ->> 'title', 'Session'), 100),
            coalesce((s ->> 'session_date')::date, current_date),
            coalesce(s ->> 'session_context', 'practice'), coalesce(s ->> 'play_format', 'singles'),
            'Generated by Dev mode. Not an analysis of a real video.')
    returning id into v_session;

    v_video := gen_random_uuid();
    insert into public.video_assets (id, owner_id, session_id, storage_path, original_filename, mime_type,
                                     byte_size, upload_status, uploaded_at)
    values (v_video, uid, v_session, uid || '/' || v_session || '/' || v_video || '.mp4',
            'dev_mock_' || (n + 1) || '.mp4', 'video/mp4', 1, 'uploaded', now());

    insert into public.analysis_jobs (owner_id, video_asset_id, session_id, status, attempts, started_at, finished_at)
    values (uid, v_video, v_session, 'completed', 1, now(), now())
    returning id into v_job;

    -- Inserted already completed, so the raw-video expiry trigger (which only
    -- fires on a status update) does not schedule deletion of a file that
    -- does not exist.
    insert into public.analysis_runs (owner_id, session_id, video_asset_id, job_id, run_number, status,
      pipeline_version, result_schema_version, result_status, result, started_at, completed_at, published_at)
    values (uid, v_session, v_video, v_job, 1, 'completed', 'dev-mock', r ->> 'schema_version',
            r ->> 'status', r, now(), now(), now())
    returning id into v_run;

    update public.analysis_jobs set current_run_id = v_run where id = v_job;
    update public.sessions set active_run_id = v_run where id = v_session;

    insert into public.analysis_results (
      job_id, owner_id, session_id, video_asset_id, run_id, schema_version, result_status, data_origin,
      pipeline_version, analyzed_duration_s, video_duration_s, fraction_analyzed, result)
    values (
      v_job, uid, v_session, v_video, v_run, r ->> 'schema_version', r ->> 'status', r ->> 'data_origin', 'dev-mock',
      (r #>> '{coverage,analyzed_duration_s}')::double precision,
      (r #>> '{video,container_duration_s}')::double precision,
      (r #>> '{coverage,fraction_of_video_analyzed}')::double precision,
      r);
    n := n + 1;
  end loop;
  return n;
end $$;

revoke all on function public.seed_dev_mock_data(jsonb) from public, anon, authenticated;
grant execute on function public.seed_dev_mock_data(jsonb) to authenticated;
